### ISSUE TITLE
依赖下载不了啊

### ISSUE THREAD

**Issue by Jadyli** [yilylong/ChannelTagView#1]

**Comment by Jadyli** [comment]
![image](https://user-images.githubusercontent.com/15962904/31808627-a902aa36-b539-11e7-8845-4da96c1c98e3.png)
![image](https://user-images.githubusercontent.com/15962904/31808636-b525e92c-b539-11e7-82e8-46b7e01dc82e.png)

**Comment by yilylong** [comment]
已修改 请看readme
