### ISSUE TITLE
点击删除

### ISSUE THREAD

**Issue by Qiaoshi96** [yilylong/ChannelTagView#3]
大佬我这边的需求是点击删除请问怎么改呀

**Comment by yilylong** [comment]
`private class ChannelAdapter extends CommonAdapter<ChannelItem> {

        public ChannelAdapter(Context context, int layoutId, List<ChannelItem> datas) {
            super(context, layoutId, datas);
        }

        @Override
        protected void convert(final ViewHolder holder, ChannelItem channelItem, final int position) {
            final BGABadgeTextView title = (BGABadgeTextView) holder.getConvertView().findViewById(R.id.item_tv);
            final ImageView drawableLeft = (ImageView) holder.getConvertView().findViewById(R.id.item_drawable_left);
            if (fixedPos == position) {
                holder.getConvertView().setBackgroundResource(fixedChannelBg);
            } else {
                holder.getConvertView().setBackgroundResource(channelItemBg);
            }
            title.setTextColor(channelItemTxColor);
            title.setTextSize(TypedValue.COMPLEX_UNIT_PX, channelItemTxSize);
            title.setText(channelItem.title);
            if (showItemDrawableLeft) {
                if (itemDrawableLeft != null) {
                    drawableLeft.setImageDrawable(itemDrawableLeft);
                }
                if (itemBgDrawableRes != -1) {
                    drawableLeft.setBackgroundResource(itemBgDrawableRes);
                }
                if (leftDrawableParams != null) {
                    drawableLeft.setLayoutParams(leftDrawableParams);
                }
                drawableLeft.setVisibility(VISIBLE);
                drawableLeft.setOnClickListener(new OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        if (null != onChannelItemClicklistener) {
                            int pos = holder.getAdapterPosition();
                            if (pos != fixedPos) {
                                ChannelItem removeChanle = addedChannels.remove(pos);
                                addedAdapter.notifyItemRemoved(pos);
                                insertToUnaddedChannel(removeChanle);
                                onChannelItemClicklistener.onItemDrawableClickListener(holder.getConvertView(), pos);
                            }
                        }
                    }
                });
            } else {
                drawableLeft.setVisibility(GONE);
            }
            if (redDotRemainderListener != null) {
                if (redDotRemainderListener.showAddedChannelBadge(title, position)) {
                    title.getBadgeViewHelper().setDragable(false);
                    redDotRemainderListener.handleAddedChannelReddot(title, position);
                } else {
                    title.hiddenBadge();
                }
            }
        }
    }
`
修改ChannelAdapter 参考drawableLeft.setOnClickListener(new OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        if (null != onChannelItemClicklistener) {
                            int pos = holder.getAdapterPosition();
                            if (pos != fixedPos) {
                                ChannelItem removeChanle = addedChannels.remove(pos);
                                addedAdapter.notifyItemRemoved(pos);
                                insertToUnaddedChannel(removeChanle);
                                onChannelItemClicklistener.onItemDrawableClickListener(holder.getConvertView(), pos);
                            }
                        }
                    }
                }); 这里  给 holder.getConvertView()设置点击事件就好了

**Comment by Qiaoshi96** [comment]
收到感谢
